### PR TITLE
Converted from bikeshed to respec

### PR DESCRIPTION
**Pull request by ianbjacobs**
HI all,

I have converted the index to respec. My next passes will be:
1) Tidy pass
2) Editorial pass

Ian

### CODE REVIEW

**Comment by domenic** [comment]
Please don't. I much prefer Bikeshed. I would like to close this.

**Comment by ianbjacobs** [comment]
Argh. I shouldn't have spent that time then. :(

My bad for not asking first. Ugh.

I converted it because (to my knowledge) the other specs of the WG are in respec and I think that enables more people to do pull requests.

Ian

**Comment by ianbjacobs** [comment]
I'll defer to the editors on this. If you close it, then I will just do my edits in the next pass. 
(Again, my bad for not asking first.)

Ian

**Comment by ianbjacobs** [comment]
One other comment: I don't know how to turn a bikeshed spec into a W3C-ready WD, so I will need help in doing that.

**Comment by domenic** [comment]
Yes, let's close. Hopefully other W3C staff can help you with the WD stuff.

**Pull request closed without merging**
