### PR TITLE
Suggest how to deal with issue 7.

### PR DESCRIPTION
**Pull request by rsolomakhin**
This patch addresses:
https://github.com/w3c/payment-method-manifest/issues/7

### CODE REVIEW

**Comment by rsolomakhin** [comment]
@domenic ptal.

@ianbjacobs @triblodon fyi.

**Comment by domenic** [comment]
I'm not sure how this prevents the payment provider from discovering the IP address of users who visit that website?

**Comment by rsolomakhin** [comment]
It's not 100% fool proof. Only the payment method owner whose payment app has been explicitly installed by the user is able to discover user's IP address. If the user does not install the corresponding payment app, the payment method owner will not be pinged.

**Comment by domenic** [comment]
Hmm, interesting. This implies that #21 should be updated to not ingest PMMs from *every* PMI passed, but allow UAs to filter to only request some of them. Do you agree?

I'll get this merged and we can continue discussion on there in #21.

**Comment by rsolomakhin** [comment]
> Do you agree?

Yep!

**Comment by domenic** [comment]
Hmm wait I'm confused again. One of the main use cases we list is:

> When the user has not yet installed a payment app for a payment method, the user agent can provide an improved user experience for procuring one.

If we only fetch PMMs for pre-installed apps, then there's no way of accomplishing this use case, right?

**Comment by rsolomakhin** [comment]
Good point. Let's use the word "may" in the spec language, so that we have some wiggle room to carefully offer just-in-time installation. This feature is not yet implemented or designed, but it's on the horizon.

**Comment by domenic** [comment]
OK, I'm going to change the last paragraph to 

> One way to mitigate this is to [=fetch payment method manifests|fetch the manifests=] only for the
[=payment apps=] that the user has installed or has explicitly expressed interest in. This confines
the risk to only sharing the user's IP address with those parties.

and merge this. Then we'll do more work in #21 to give details.

**Pull request merged**
